<a href="https://colab.research.google.com/github/SasiwimonV/Basicprog_DataViz65/blob/main/%E0%B8%95%E0%B8%AD%E0%B8%99%E0%B8%A5%E0%B9%88%E0%B8%B2%E0%B8%87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#ปริมาณฝน

In [3]:
ks = pd.read_excel('/content/drive/MyDrive/ข้อมูลกรมอุตุตอนล่าง/ปริมาณน้ำฝน/ปริมาณน้ำฝนมุกดาหาร.xlsx',header=[0])

In [4]:
ks.columns

Index([       'สถานี', 'วัน/เดือน/ปี',              1,              2,
                    3,              4,              5,              6,
                    7,              8,              9,             10,
                   11,             12,             13,             14,
                   15,             16,             17,             18,
                   19,             20,             21,             22,
                   23,             24,             25,             26,
                   27,             28,             29,             30,
                   31,          'รวม',       'เฉลี่ย'],
      dtype='object')

In [5]:
ks.head()

,สถานี,วัน/เดือน/ปี,1,2,3,4,5,6,7,8,...,24,25,26,27,28,29,30,31,รวม,เฉลี่ย
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0.0,0.000000
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,NaN,NaN,NaN,0.4,0.014286
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,2.2,0.073333
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,0,0,2,0,2,22.3,2.7,2.4,...,0,0,0,19.7,0.0,52.5,0,NaN,119.1,4.106897
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,0,8.7,3.2,4.2,0,0.2,0.3,31.7,...,0,0,14.9,0,0.0,23.9,0,37.7,143.5,4.629032

##dropna() แทนค่า T

In [6]:
ks.fillna(method='ffill' , inplace=True)
ks

,สถานี,วัน/เดือน/ปี,1,2,3,4,5,6,7,8,...,24,25,26,27,28,29,30,31,รวม,เฉลี่ย
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0.0,0.000000
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0.4,0.014286
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,2.2,0.073333
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,0,0,2,0,2,22.3,2.7,2.4,...,0,0,0,19.7,0.0,52.5,0,0,119.1,4.106897
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,0,8.7,3.2,4.2,0,0.2,0.3,31.7,...,0,0,14.9,0,0.0,23.9,0,37.7,143.5,4.629032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-08-01 00:00:00,47.7,12.4,7.2,3.3,1.2,0,0,24.8,...,2.5,0,1.9,0.2,11.8,8.3,0,0.2,240.6,7.761290
116,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-09-01 00:00:00,1,2.8,18.4,38.6,136.1,12.7,15.9,71.4,...,0,25.8,40.2,42.7,11.0,15.4,8.4,-,599.6,19.986667
117,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-10-01 00:00:00,0,0,0,0.1,0,26.4,4.8,6.5,...,0,1.6,0,0,0.0,0,0,0,42.7,1.377419
118,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-11-01 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,-,0.3,0.010000
119,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-12-01 00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0,0,0.0,0.000000

In [7]:
ks.replace('T', 0, inplace=True)
ks.replace('-', 0, inplace=True)
ks

,สถานี,วัน/เดือน/ปี,1,2,3,4,5,6,7,8,...,24,25,26,27,28,29,30,31,รวม,เฉลี่ย
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.014286
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.2,0.073333
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,0.0,0.0,2.0,0.0,2.0,22.3,2.7,2.4,...,0.0,0.0,0.0,19.7,0.0,52.5,0.0,0.0,119.1,4.106897
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,0.0,8.7,3.2,4.2,0.0,0.2,0.3,31.7,...,0.0,0.0,14.9,0.0,0.0,23.9,0.0,37.7,143.5,4.629032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-08-01 00:00:00,47.7,12.4,7.2,3.3,1.2,0.0,0.0,24.8,...,2.5,0.0,1.9,0.2,11.8,8.3,0.0,0.2,240.6,7.761290
116,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-09-01 00:00:00,1.0,2.8,18.4,38.6,136.1,12.7,15.9,71.4,...,0.0,25.8,40.2,42.7,11.0,15.4,8.4,0.0,599.6,19.986667
117,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-10-01 00:00:00,0.0,0.0,0.0,0.1,0.0,26.4,4.8,6.5,...,0.0,1.6,0.0,0.0,0.0,0.0,0.0,0.0,42.7,1.377419
118,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-11-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.010000
119,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-12-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [8]:
ks = ks[['สถานี','วัน/เดือน/ปี', 'เฉลี่ย']]
ks

,สถานี,วัน/เดือน/ปี,เฉลี่ย
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,0.000000
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,0.014286
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,0.073333
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,4.106897
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,4.629032
...,...,...,...
115,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-08-01 00:00:00,7.761290
116,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-09-01 00:00:00,19.986667
117,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-10-01 00:00:00,1.377419
118,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-11-01 00:00:00,0.010000
119,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-12-01 00:00:00,0.000000

In [9]:
S1=ks.rename(columns={'เฉลี่ย': 'ปริมาณน้ำฝน'}, inplace=True)
ks

<ipython-input-9-341520cc01c4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  S1=ks.rename(columns={'เฉลี่ย': 'ปริมาณน้ำฝน'}, inplace=True)

,สถานี,วัน/เดือน/ปี,ปริมาณน้ำฝน
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,0.000000
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,0.014286
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,0.073333
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,4.106897
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,4.629032
...,...,...,...
115,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-08-01 00:00:00,7.761290
116,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-09-01 00:00:00,19.986667
117,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-10-01 00:00:00,1.377419
118,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-11-01 00:00:00,0.010000
119,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-12-01 00:00:00,0.000000

#อุณหภูมิสูงสุด

In [29]:
mks =pd.read_excel('/content/drive/MyDrive/ข้อมูลกรมอุตุตอนล่าง/อุณหภูมิสูงสุด/max จังหวัดมุกดาหาร 51-66.xls',header=[0])

In [30]:
mks.columns

Index([       'สถานี', 'วัน/เดือน/ปี',          '1  ',          '2  ',
                '3  ',          '4  ',          '5  ',          '6  ',
                '7  ',          '8  ',          '9  ',         '10  ',
                    1,             12,             13,             14,
                   15,             16,             17,             18,
                   19,             20,             21,             22,
                   23,             24,             25,             26,
                   27,             28,             29,             30,
                   31,          'รวม',       'เฉลี่ย'],
      dtype='object')

In [31]:
SD = pd.concat([mks])
SD.shape

(120, 35)

In [32]:
SD.columns
SD.head()

,สถานี,วัน/เดือน/ปี,1,2,3,4,5,6,7,8,...,24,25,26,27,28,29,30,31,รวม,เฉลี่ย
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,26.9,29.4,31.9,29.2,29.6,30.8,32.7,33.6,...,28,30.2,29.8,30,31.2,30.5,29.3,31.1,856.7,28.556667
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,31.9,34.6,35.5,32.7,32.2,34.1,35,35.4,...,33.6,35.7,34.6,34.5,35.3,-,-,-,896.7,32.025000
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,37.8,37.9,38.3,38.6,37.8,36.6,36.5,36.2,...,33.6,35.5,36.7,36.7,38.0,38.8,39.5,39.8,1094.1,36.470000
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,40.6,37.8,36.9,33.7,32,31.8,34.9,35.0,...,39,39.6,39.2,34.7,34.0,31.7,32.9,-,1077.3,35.910000
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,33.2,34.2,32.8,34.4,36,30.1,33.9,36.0,...,39.2,38.2,39.0,35.5,36.0,37.6,36.9,34.9,1088.9,36.296667

In [34]:
SD = SD.dropna()
SD

,สถานี,วัน/เดือน/ปี,1,2,3,4,5,6,7,8,...,24,25,26,27,28,29,30,31,รวม,เฉลี่ย
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,26.9,29.4,31.9,29.2,29.6,30.8,32.7,33.6,...,28,30.2,29.8,30,31.2,30.5,29.3,31.1,856.7,28.556667
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,31.9,34.6,35.5,32.7,32.2,34.1,35,35.4,...,33.6,35.7,34.6,34.5,35.3,-,-,-,896.7,32.025000
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,37.8,37.9,38.3,38.6,37.8,36.6,36.5,36.2,...,33.6,35.5,36.7,36.7,38.0,38.8,39.5,39.8,1094.1,36.470000
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,40.6,37.8,36.9,33.7,32,31.8,34.9,35.0,...,39,39.6,39.2,34.7,34.0,31.7,32.9,-,1077.3,35.910000
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,33.2,34.2,32.8,34.4,36,30.1,33.9,36.0,...,39.2,38.2,39.0,35.5,36.0,37.6,36.9,34.9,1088.9,36.296667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-08-01 00:00:00,29.9,29.4,28.9,30.1,31.4,31.3,29.4,33.7,...,31.7,33.5,33.4,32.6,35.2,28,31.6,32.6,1019.5,32.887097
116,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-09-01 00:00:00,33.9,32.8,34.5,33.1,33.6,30.4,31,31.6,...,34.6,32.3,25.4,30.5,30.4,30.8,32.1,-,956.9,31.896667
117,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-10-01 00:00:00,34.1,34.8,33.9,34.2,34.6,32.8,30.5,30.5,...,29.7,31.8,33.7,33.3,34.4,34.6,33.8,31.5,1012.0,32.645161
118,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-11-01 00:00:00,32.0,33.7,34.8,34.6,35,35.0,34.9,33.2,...,29.4,31.4,31.4,31.4,29.7,31.1,33.5,-,965.9,32.196667
119,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-12-01 00:00:00,31.5,31.4,30.5,32.5,33.5,34.1,30.4,32.5,...,23.4,24.8,28.4,30.4,31.6,32.2,33.1,33.2,961.7,31.022581

In [35]:
SD.replace('T', 0, inplace=True)
SD.replace('-', 0, inplace=True)
SD

,สถานี,วัน/เดือน/ปี,1,2,3,4,5,6,7,8,...,24,25,26,27,28,29,30,31,รวม,เฉลี่ย
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,26.9,29.4,31.9,29.2,29.6,30.8,32.7,33.6,...,28,30.2,29.8,30,31.2,30.5,29.3,31.1,856.7,28.556667
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,31.9,34.6,35.5,32.7,32.2,34.1,35.0,35.4,...,33.6,35.7,34.6,34.5,35.3,0.0,0.0,0.0,896.7,32.025000
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,37.8,37.9,38.3,38.6,37.8,36.6,36.5,36.2,...,33.6,35.5,36.7,36.7,38.0,38.8,39.5,39.8,1094.1,36.470000
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,40.6,37.8,36.9,33.7,32,31.8,34.9,35.0,...,39,39.6,39.2,34.7,34.0,31.7,32.9,0.0,1077.3,35.910000
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,33.2,34.2,32.8,34.4,36,30.1,33.9,36.0,...,39.2,38.2,39.0,35.5,36.0,37.6,36.9,34.9,1088.9,36.296667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-08-01 00:00:00,29.9,29.4,28.9,30.1,31.4,31.3,29.4,33.7,...,31.7,33.5,33.4,32.6,35.2,28.0,31.6,32.6,1019.5,32.887097
116,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-09-01 00:00:00,33.9,32.8,34.5,33.1,33.6,30.4,31.0,31.6,...,34.6,32.3,25.4,30.5,30.4,30.8,32.1,0.0,956.9,31.896667
117,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-10-01 00:00:00,34.1,34.8,33.9,34.2,34.6,32.8,30.5,30.5,...,29.7,31.8,33.7,33.3,34.4,34.6,33.8,31.5,1012.0,32.645161
118,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-11-01 00:00:00,32.0,33.7,34.8,34.6,35,35.0,34.9,33.2,...,29.4,31.4,31.4,31.4,29.7,31.1,33.5,0.0,965.9,32.196667
119,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-12-01 00:00:00,31.5,31.4,30.5,32.5,33.5,34.1,30.4,32.5,...,23.4,24.8,28.4,30.4,31.6,32.2,33.1,33.2,961.7,31.022581

In [36]:
SD = SD[['สถานี','วัน/เดือน/ปี', 'เฉลี่ย']]
SD

,สถานี,วัน/เดือน/ปี,เฉลี่ย
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,28.556667
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,32.025000
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,36.470000
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,35.910000
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,36.296667
...,...,...,...
115,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-08-01 00:00:00,32.887097
116,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-09-01 00:00:00,31.896667
117,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-10-01 00:00:00,32.645161
118,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-11-01 00:00:00,32.196667
119,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-12-01 00:00:00,31.022581

In [38]:
S2=SD.rename(columns={'เฉลี่ย': 'อุณหภูมิสูงสุด'}, inplace=True)
SD

<ipython-input-38-b13df79b1b05>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  S2=SD.rename(columns={'เฉลี่ย': 'อุณหภูมิสูงสุด'}, inplace=True)

,สถานี,วัน/เดือน/ปี,ปริมาณน้ำฝน
0,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-01-01 00:00:00,28.556667
1,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-02-01 00:00:00,32.025000
2,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-03-01 00:00:00,36.470000
3,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-04-01 00:00:00,35.910000
4,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2557-05-01 00:00:00,36.296667
...,...,...,...
115,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-08-01 00:00:00,32.887097
116,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-09-01 00:00:00,31.896667
117,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-10-01 00:00:00,32.645161
118,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-11-01 00:00:00,32.196667
119,383201 : สถานีอุตุนิยมวิทยามุกดาหาร อ.เมือ...,2566-12-01 00:00:00,31.022581

#อุณหภูมิต่ำสุด

In [39]:
nks =pd.read_excel('/content/drive/MyDrive/ข้อมูลกรมอุตุตอนล่าง/อุณหภูมิต่ำสุด/min จังหวัดมุกดาหาร ปี 2551 - 2566.xls',header=[0])

In [40]:
nks.columns

Index([       'สถานี', 'วัน/เดือน/ปี',          '1  ',          '2  ',
                '3  ',          '4  ',          '5  ',          '6  ',
                '7  ',          '8  ',          '9  ',         '10  ',
                    1,             12,             13,             14,
                   15,             16,             17,             18,
                   19,             20,             21,             22,
                   23,             24,             25,             26,
                   27,             28,             29,             30,
                   31,          'รวม',       'เฉลี่ย'],
      dtype='object')

In [22]:
Sn = pd.concat([nks,nbu])
Sn.shape

(28, 55)

In [23]:
Sn.columns
Sn.head()

,อุณหภูมิต่ำสุดเฉลี่ยรายเดือน (องศาเซลเซียส),วันที่,1,2,3,4,5,6,7,8,...,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,จังหวัด
1,Lat 14.58.00 Long 102.05.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,นครราชสีมา
2,วันที่,NaN,1.0,2,NaN,3.0,4,NaN,5,NaN,...,28,NaN,29,NaN,30.0,31.0,เฉลี่ย,ต่ำสุด,วันที่,นครราชสีมา
3,เดือน,ม.ค.,20.7,21.5,NaN,22.2,21.4,NaN,22.5,NaN,...,19.1,NaN,16.8,NaN,18.0,18.7,21.5,16.8,29,นครราชสีมา
4,NaN,ก.พ.,19.1,22,NaN,21.8,21,NaN,20.7,NaN,...,20.7,NaN,NaN,NaN,NaN,NaN,20.3,16.3,13,นครราชสีมา
5,NaN,มี.ค.,21.2,19.3,NaN,19.7,19.5,NaN,23,NaN,...,21.7,NaN,24,NaN,23.2,25.8,23.5,19.3,2,นครราชสีมา

In [24]:
Sn.fillna(method='ffill' , inplace=True)
Sn

,อุณหภูมิต่ำสุดเฉลี่ยรายเดือน (องศาเซลเซียส),วันที่,1,2,3,4,5,6,7,8,...,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,จังหวัด
1,Lat 14.58.00 Long 102.05.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,นครราชสีมา
2,วันที่,NaN,1.0,2,NaN,3.0,4,NaN,5,NaN,...,28,NaN,29,NaN,30.0,31.0,เฉลี่ย,ต่ำสุด,วันที่,นครราชสีมา
3,เดือน,ม.ค.,20.7,21.5,NaN,22.2,21.4,NaN,22.5,NaN,...,19.1,NaN,16.8,NaN,18.0,18.7,21.5,16.8,29,นครราชสีมา
4,เดือน,ก.พ.,19.1,22,NaN,21.8,21,NaN,20.7,NaN,...,20.7,NaN,16.8,NaN,18.0,18.7,20.3,16.3,13,นครราชสีมา
5,เดือน,มี.ค.,21.2,19.3,NaN,19.7,19.5,NaN,23,NaN,...,21.7,NaN,24,NaN,23.2,25.8,23.5,19.3,2,นครราชสีมา
6,เดือน,เม.ย.,22.7,20.8,NaN,22.2,24.8,NaN,25.5,NaN,...,*23.2,-27.0,23.2,NaN,25.4,25.8,25,20.8,2,นครราชสีมา
7,เดือน,พ.ค.,25.9,27.2,NaN,26.9,*25.3,-27.3,24.1,NaN,...,25.4,-27.0,25.1,NaN,25.7,25.4,25.5,23.9,7,นครราชสีมา
8,เดือน,มิ.ย.,25.1,25.7,NaN,25.0,24,-27.3,25.2,NaN,...,24.9,-27.0,*24.5,-25.7,24.6,25.4,25.1,23.2,10,นครราชสีมา
9,เดือน,ก.ค.,25.8,24.6,NaN,24.5,*23.1,-24.5,23.2,NaN,...,25.3,-27.0,25,-25.7,25.7,26.0,25,23.1,4,นครราชสีมา
10,เดือน,ส.ค.,26.0,25.7,NaN,25.2,26.2,-24.5,*25.2,-26.1,...,24.4,-27.0,24.2,-25.7,24.6,24.8,25.2,23.2,19,นครราชสีมา
11,เดือน,ก.ย.,25.5,26.5,NaN,24.7,26.1,-24.5,*25.0,-25.5,...,*24.2,-25.2,24,-25.7,24.4,24.8,24.7,22.7,12,นครราชสีมา
12,เดือน,ต.ค.,24.1,*23.9,-25.5,23.0,24.1,-24.5,24,-25.5,...,22.5,-25.2,23.3,-25.7,22.0,20.5,24.1,20.5,31,นครราชสีมา
13,เดือน,พ.ย.,23.0,22.2,-25.5,21.6,18.8,-24.5,*20.4,-22.5,...,21,-25.2,20.9,-25.7,23.9,20.5,22.4,18.5,25,นครราชสีมา
14,เดือน,ธ.ค.,23.1,21.9,-25.5,20.8,21.3,-24.5,22.5,-22.5,...,20,-25.2,20,-25.7,20.9,21.0,19.7,12.8,19,นครราชสีมา
1,Lat 14.35.00 Long 102.48.00,ธ.ค.,23.1,21.9,-25.5,20.8,21.3,-24.5,22.5,-22.5,...,20,-25.2,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
2,วันที่,ธ.ค.,1.0,2,-25.5,3.0,4,-24.5,5.0,6.0,...,ต่ำสุด,วันที่,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
3,เดือน,ม.ค.,19.9,20.2,-25.5,20.7,20.6,-24.5,21.1,22.4,...,15,29,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
4,เดือน,ก.พ.,15.2,*21.5,-22.0,20.8,20.8,-24.5,19.0,16.1,...,14.5,13,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
5,เดือน,มี.ค.,19.8,18.5,-22.0,17.0,16.3,-24.5,21.2,22.5,...,16.3,4,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
6,เดือน,เม.ย.,21.8,19.8,-22.0,20.7,23.5,-24.5,23.4,23.5,...,19.8,2,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
7,เดือน,พ.ค.,25.5,25,-22.0,25.4,*24.2,-26.0,22.4,23.0,...,22.4,5,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
8,เดือน,มิ.ย.,24.6,25.4,-22.0,25.4,24.1,-26.0,25.7,24.7,...,23.5,28,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
9,เดือน,ก.ค.,24.2,24,-22.0,24.6,24.3,-26.0,23.0,23.6,...,22.6,27,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
10,เดือน,ส.ค.,24.8,24.5,-22.0,24.4,25.1,-26.0,25.2,25.0,...,23,26,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
11,เดือน,ก.ย.,23.5,24,-22.0,24.4,25,-26.0,25.4,25.2,...,22.2,21,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
12,เดือน,ต.ค.,23.5,23.4,-22.0,23.1,23.7,-26.0,23.5,24.3,...,18.8,31,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
13,เดือน,พ.ย.,20.5,20.7,-22.0,20.3,18.4,-26.0,20.0,19.8,...,16.7,25,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
14,เดือน,ธ.ค.,22.1,20.6,-22.0,20.5,21,-26.0,21.0,19.3,...,11.2,20,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์

In [25]:
Sn = Sn.dropna()
Sn

,อุณหภูมิต่ำสุดเฉลี่ยรายเดือน (องศาเซลเซียส),วันที่,1,2,3,4,5,6,7,8,...,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,จังหวัด
12,เดือน,ต.ค.,24.1,*23.9,-25.5,23.0,24.1,-24.5,24,-25.5,...,22.5,-25.2,23.3,-25.7,22.0,20.5,24.1,20.5,31,นครราชสีมา
13,เดือน,พ.ย.,23.0,22.2,-25.5,21.6,18.8,-24.5,*20.4,-22.5,...,21,-25.2,20.9,-25.7,23.9,20.5,22.4,18.5,25,นครราชสีมา
14,เดือน,ธ.ค.,23.1,21.9,-25.5,20.8,21.3,-24.5,22.5,-22.5,...,20,-25.2,20,-25.7,20.9,21.0,19.7,12.8,19,นครราชสีมา
1,Lat 14.35.00 Long 102.48.00,ธ.ค.,23.1,21.9,-25.5,20.8,21.3,-24.5,22.5,-22.5,...,20,-25.2,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
2,วันที่,ธ.ค.,1.0,2,-25.5,3.0,4,-24.5,5.0,6.0,...,ต่ำสุด,วันที่,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
3,เดือน,ม.ค.,19.9,20.2,-25.5,20.7,20.6,-24.5,21.1,22.4,...,15,29,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
4,เดือน,ก.พ.,15.2,*21.5,-22.0,20.8,20.8,-24.5,19.0,16.1,...,14.5,13,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
5,เดือน,มี.ค.,19.8,18.5,-22.0,17.0,16.3,-24.5,21.2,22.5,...,16.3,4,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
6,เดือน,เม.ย.,21.8,19.8,-22.0,20.7,23.5,-24.5,23.4,23.5,...,19.8,2,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
7,เดือน,พ.ค.,25.5,25,-22.0,25.4,*24.2,-26.0,22.4,23.0,...,22.4,5,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
8,เดือน,มิ.ย.,24.6,25.4,-22.0,25.4,24.1,-26.0,25.7,24.7,...,23.5,28,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
9,เดือน,ก.ค.,24.2,24,-22.0,24.6,24.3,-26.0,23.0,23.6,...,22.6,27,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
10,เดือน,ส.ค.,24.8,24.5,-22.0,24.4,25.1,-26.0,25.2,25.0,...,23,26,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
11,เดือน,ก.ย.,23.5,24,-22.0,24.4,25,-26.0,25.4,25.2,...,22.2,21,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
12,เดือน,ต.ค.,23.5,23.4,-22.0,23.1,23.7,-26.0,23.5,24.3,...,18.8,31,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
13,เดือน,พ.ย.,20.5,20.7,-22.0,20.3,18.4,-26.0,20.0,19.8,...,16.7,25,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์
14,เดือน,ธ.ค.,22.1,20.6,-22.0,20.5,21,-26.0,21.0,19.3,...,11.2,20,20,-25.7,20.9,21.0,19.7,12.8,19,บุรีรัมย์

In [26]:
Sn = Sn[['วันที่', 'รวม']]

In [27]:
S3=Sn.rename(columns={'รวม': 'อุณภูมิต่ำสุด','วันที่':'เดือน'}, inplace=True)
Sn

<ipython-input-27-1141a88d6c14>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  S3=Sn.rename(columns={'รวม': 'อุณภูมิต่ำสุด','วันที่':'เดือน'}, inplace=True)

    เดือน อุณภูมิต่ำสุด
12   ต.ค.          25.5
13   พ.ย.          23.4
14   ธ.ค.          12.8
1    ธ.ค.          12.8
2    ธ.ค.            24
3    ม.ค.          17.3
4    ก.พ.          23.3
5   มี.ค.         *22.2
6   เม.ย.            25
7    พ.ค.            23
8   มิ.ย.          24.4
9    ก.ค.            24
10   ส.ค.          24.7
11   ก.ย.          23.6
12   ต.ค.          23.6
13   พ.ย.          18.3
14   ธ.ค.          18.4

In [28]:
merge1 = Speed.merge(SD, how ='left', left_on=['เดือน',], right_on=['เดือน'])
merge2 = merge1.merge(Sn, how ='left', left_on=['เดือน',], right_on=['เดือน'])
merge2

NameError: name 'Speed' is not defined

#แบ่งข้อมูล

In [ ]:
c=merge2[['เดือน','ปริมาณน้ำฝน','จังหวัด','อุณหภูมิสูงสุด','อุณหภูมิต่ำสุด']]

In [ ]:
#แบ่งข้อมูลเป็นชุดฝึกสอน และชุดทดสอบ
c_train=c.iloc[:120,:]
c_test=c.iloc[:24,:]

In [ ]:
c_train

In [ ]:
c_test

In [ ]:
import matplotib.pyplot as plt
from statsmodels.graphics.tsaplots import plot acf
import statsmodels.api as sm
import pandas as pd


# สร้าง subplot 2x1
fig, axes = plt.subplots(2, 1, figsize=(10, 6))

# วาดกราฟของ 'cP_ptt' ใน subplot แรก
axes[0],plot(c.index, c['], label='')
axes[0].set_ title('Close Price for"
axes[0].set_xlabel('')
axes[0].set_ylabel('Close Price'")

# พล็อตกราฟ ACF ใน subplot ที่สอง
sm.graphics.tsa.plot_acf(c_train(''], lags=130, ax=axes[1], marker=' )
axes[1].set_title('Autocorrelation Function (ACF) for ')
axes[1].set_xlabel('Lag')
axes[1].set_ylabel("ACF)

# แสดงกราฟเทียบระหว่างกราฟข้อมูลจริงกับกราฟ ACF
plt.tight_layout()
plt.show()

In [ ]:
import pandas as pd
from statsmodels.tsa.stattools import adfuller


# ทำ ADF Test
adf_result = adfuller(c_train[''])

# แสดงผลลัพธ์
print("ADF Statistic:", adf_result[이])
print("p-value:", adf_result[1])
print("Critical Values:", adf_result[4])